version: '3'
services:
    # Database container
    database:
        image: postgres
        env_file:
            - database.env
        ports:
            - "5432:5432"
        volumes:
            - ./database-data/:/var/lib/postgresql/data/
    
    # Backend python flask application
    backend:
        build: 
            context: . 
            dockerfile: Dockerfile.backend
        ports: 
            - 5000:5000
        depends_on: 
            - database
        restart:
            always
    
    # Frontend react application
    frontend:
        build: 
            context: . 
            dockerfile: Dockerfile.frontend
        ports:
            - 3000:80
        volumes:
            - ./frontend-react:/app
            - /frontend-react/node_modules
        depends_on: 
            - backend
        stdin_open: 
            true