version: '3'
services:
    # Backend python flask application
    backend:
        build: 
            context: . 
            dockerfile: Dockerfile.backend
        ports: 
            - 5000:5000
        restart:
            always
    # Frontend react application
    frontend:
        build: 
            context: . 
            dockerfile: Dockerfile.frontend
        ports:
            - 3000:80
        volumes:
            - ./frontend-react:/app
            - /frontend-react/node_modules
        depends_on: 
            - backend
        stdin_open: 
            true