version: '3'
services:
    # Database container
    db:
        image: "postgres" 
        env_file:
          - database.env
        volumes:
          - ./database-data/:/var/lib/postgresql/data/

    # Backend python flask application
    backend:
        build: 
            context: . 
            dockerfile: Dockerfile.backend-dev
        ports: 
            - 5000:5000
        volumes: 
            - ./backend-python:/app
        depends_on: 
            - db
        restart:
            always
            
    # Frontend react application
    frontend:
        build: 
            context: . 
            dockerfile: Dockerfile.frontend-dev
        ports:
            - 3000:3000
        volumes:
            - ./frontend-react:/app
            - /frontend-react/node_modules
        depends_on: 
            - backend
        stdin_open: 
            true