version: '3'
services:
    # Backend python flask application
    backend:
        build: 
            context: . 
            dockerfile: Dockerfile.backend-dev
        ports: 
            - 5000:5000
        volumes: 
            - ./backend-python:/app
        restart:
            always
    # Frontend react application
    frontend:
        build: 
            context: . 
            dockerfile: Dockerfile.frontend-dev
        ports:
            - 3000:3000
        volumes:
            - ./frontend-react:/app
            - /frontend-react/node_modules
        depends_on: 
            - backend
        stdin_open: 
            true